### ISSUE TITLE
Contribution ideas

### ISSUE THREAD

**Issue by notlober** [karpathy/nano-llama31#7]
Hi, I was looking to open source contribute this repo, I saw these in TODO:

“think through support for Llama 3 models > 8B in size”
“make finetuning more full featured, more similar to nanoGPT (mixed precision, DDP, bells and whistles etc.)”

first of all I first think nanoGPT’s “nano” is not equal to nanoLlama31’s “nano”, I mean the model size differences are big, x < 1.5b and x = 8b, 70b, 405b, so nanoGPT’s recipe won’t directly fit this repo, for example only distributed data paralel for parallelism is not ideal in most scenarios especially for models larger than 8b and bigger batch sizes for all model sizes.

so I think about adding support for model parallelism via deepspeed zero or megatron lm etc..

Is this a good idea? If yes, which one would be preferred?

**Comment by rasbt** [comment]
I think DeepSpeed Zero should be equivalent to PyTorch's FSDP implementation. 

From my LitGPT work, for the 8B model, PyTorch's FSDP should be fine for multi-GPU and multi-node training (we originally used DeepSpeed for that but then switched to FSDP because it's more native in PyTorch):

https://github.com/Lightning-AI/litgpt/blob/627949db5c032089bd68bb889ea989bfff654e18/litgpt/finetune/full.py#L98-L105

However, yeah, for the 70B model you'd probably need model 3D or 4D parallelism.
